"""Public-official release checklist (v0.3.5, req 4).

`ceb hosted release-checklist create` renders a human-readable, commit-safe
Markdown checklist from a readiness report (ideally produced by
`ceb hosted readiness declare --json`) and a public release manifest.

The output contains ONLY hashes, fingerprints, image digests, policy, and
limitations — never key material or private paths — so it is safe to commit
and publish alongside a season's leaderboard. It is governance, not a security
barrier: the real gate is `ceb hosted readiness declare`.
"""

import json
from pathlib import Path

from ceb import __version__
from ceb.sanitize import SanitizedError

SCHEMA = "ceb.hosted.release_checklist/v1"


class ReleaseChecklistError(SanitizedError, ValueError):
    pass


def _load_json(path, label):
    if not path:
        return {}
    p = Path(path)
    if not p.is_file():
        raise ReleaseChecklistError("%s not found" % label,
                                    "%s not found: %s" % (label, p))
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ReleaseChecklistError("%s is not valid JSON" % label,
                                    "%s parse error: %s" % (label, exc))
    if not isinstance(data, dict):
        raise ReleaseChecklistError("%s must be a JSON object" % label)
    return data


def _yn(value):
    return "yes" if value else "NO"


def render_checklist(*, track, readiness, manifest, manifest_hash=None):
    """Render the commit-safe Markdown checklist. `readiness` and `manifest`
    are parsed JSON dicts (either may be empty)."""
    track = str(track).upper()
    cert = readiness.get("declaration_certificate") or {}
    version = (cert.get("benchmark_version") or readiness.get("version")
               or manifest.get("benchmark_version") or __version__)
    declaration = readiness.get("public_official_declaration", "unknown")
    ready = bool(readiness.get("ready"))
    blocking = readiness.get("blocking_failures") or []
    git_commit = manifest.get("git_commit") or cert.get("git_commit")
    rel_hash = (manifest_hash or cert.get("release_manifest_hash"))

    lines = []
    lines.append("# chess_en_bench — public-official release checklist")
    lines.append("")
    lines.append("> Generated by `ceb hosted release-checklist create`. "
                 "Commit-safe: hashes/fingerprints/policy only, no secrets.")
    lines.append("")
    lines.append("**Do NOT declare this deployment official unless the readiness "
                 "declaration below is `ready`.** The authoritative gate is "
                 "`ceb hosted readiness declare --track %s` (or "
                 "`readiness check --strict-public-official`)." % track)
    lines.append("")

    lines.append("## Declaration")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| --- | --- |")
    lines.append("| Benchmark version | `%s` |" % version)
    lines.append("| Track | `%s` |" % track)
    lines.append("| Git commit | `%s` |" % (git_commit or "-"))
    lines.append("| Readiness declaration | **%s** |" % declaration)
    lines.append("| Strict readiness ready | %s |" % _yn(ready))
    lines.append("| Blocking failures | %s |"
                 % (", ".join("`%s`" % b for b in blocking) if blocking else "none"))
    lines.append("| Release manifest hash | `%s` |" % (rel_hash or "-"))
    lines.append("")

    lines.append("## Trust anchors (from the release manifest)")
    lines.append("")
    lines.append("| Anchor | Value |")
    lines.append("| --- | --- |")
    lines.append("| Official eval pack id | `%s` |"
                 % (manifest.get("official_eval_pack_id") or "-"))
    lines.append("| Official eval pack hash | `%s` |"
                 % (manifest.get("official_eval_pack_hash")
                    or cert.get("official_eval_pack_hash") or "-"))
    lines.append("| Eval pack season | `%s` |" % (manifest.get("season") or "-"))
    lines.append("| Operator public key fingerprint | `%s` |"
                 % (manifest.get("operator_public_key_fingerprint")
                    or cert.get("operator_public_key_fingerprint") or "-"))
    lines.append("| Engine jail image | `%s` |"
                 % (manifest.get("engine_jail_image") or "-"))
    lines.append("| Engine jail image digest | `%s` |"
                 % (manifest.get("engine_jail_image_digest") or "-"))
    if track in ("B", "BOTH"):
        lines.append("| Track B baseline trust mode | `%s` |"
                     % (manifest.get("track_b_baseline_trust_mode") or "-"))
        lines.append("| Track B baseline hash | `%s` |"
                     % (manifest.get("track_b_baseline_hash")
                        or cert.get("track_b_baseline_hash") or "-"))
        lines.append("| Track B build wrapper hash | `%s` |"
                     % (manifest.get("track_b_build_wrapper_hash")
                        or cert.get("build_wrapper_hash") or "-"))
        lines.append("| Build jail image digest | `%s` |"
                     % (manifest.get("build_jail_image_digest") or "-"))
    lines.append("")

    bench = manifest.get("bench_policy")
    if bench:
        lines.append("**Track B bench policy:** min NPS ratio "
                     "`%s`; supported is required for a verified result; a "
                     "failed bench or `--dev-allow-no-bench` downgrades to "
                     "diagnostic (never verified)."
                     % bench.get("min_nps_ratio"))
        lines.append("")

    lines.append("## Leaderboard policy")
    lines.append("")
    lines.append(manifest.get("leaderboard_policy")
                 or "verified results only; one entry per run = best verified "
                    "result; smoke/diagnostic never appear.")
    lines.append("")

    lines.append("## Known limitations")
    lines.append("")
    limitations = (manifest.get("known_limitations")
                   or cert.get("known_limitations") or [])
    if limitations:
        for item in limitations:
            lines.append("- %s" % item)
    else:
        lines.append("- (none recorded)")
    lines.append("")

    lines.append("## Verify it yourself")
    lines.append("")
    lines.append("Re-run the declaration gate against the real operator assets:")
    lines.append("")
    lines.append("```bash")
    lines.append("ceb hosted readiness declare \\")
    lines.append("    --db runs/hosted.sqlite \\")
    lines.append("    --eval-pack <official-pack> \\")
    lines.append("    --public-key op.pub.pem --signing-key op.pem \\")
    lines.append("    --official-pack-hash <sha256:...> \\")
    if track in ("B", "BOTH"):
        lines.append("    --build-wrapper <trusted-wrapper.sh> \\")
        lines.append("    --build-wrapper-hash <sha256:...> \\")
        lines.append("    --track-b-baseline-hash <sha256:...> \\")
        lines.append("    --track-b-baseline-engine <bench-capable-stockfish> \\")
    lines.append("    --track %s --release-manifest release.json --json" % track)
    lines.append("```")
    lines.append("")
    lines.append("Verify a published result and the release manifest "
                 "(authentic only with the out-of-band public key):")
    lines.append("")
    lines.append("```bash")
    lines.append("ceb hosted verify-result --result official_result.json \\")
    lines.append("    --public-key op.pub.pem")
    lines.append("ceb hosted release-manifest verify --manifest release.json \\")
    lines.append("    --public-key op.pub.pem")
    lines.append("```")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_release_checklist(*, track, readiness_report=None,
                            release_manifest=None, manifest_hash=None):
    """Load the inputs and render the checklist Markdown string."""
    readiness = _load_json(readiness_report, "readiness report")
    manifest = _load_json(release_manifest, "release manifest")
    if manifest_hash is None and release_manifest:
        from ceb.hosted.metadata import hash_file
        try:
            manifest_hash = hash_file(release_manifest)
        except OSError:
            manifest_hash = None
    return render_checklist(track=track, readiness=readiness, manifest=manifest,
                            manifest_hash=manifest_hash)
